# Generated by Django 2.2.5 on 2019-12-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='project',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
