# Generated by Django 3.0.7 on 2020-08-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_auto_20191202_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startupimage', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='links',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='links',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
