# Generated by Django 3.0.7 on 2020-08-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_auto_20200805_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='summary',
        ),
        migrations.AddField(
            model_name='education',
            name='Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Percentage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Qualifications',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='end_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
