# Generated by Django 2.2.15 on 2020-08-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0005_auto_20200806_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100)),
                ('scale', models.IntegerField()),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Personal', 'Personal'), ('ZF', 'ZF'), ('Visteon', 'Visteon')], default='Technical', max_length=20)),
            ],
        ),
    ]
