# Generated by Django 2.2.15 on 2020-08-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0006_technicalskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=100)),
                ('link', models.TextField(blank=True, max_length=1000, null=True)),
                ('pictures', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
