# Generated by Django 2.2.15 on 2020-08-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0007_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('Description', models.TextField()),
                ('link', models.TextField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(choices=[('Project', 'Project'), ('Papers', 'Papers'), ('Workshops', 'Workshops')], default='Papers', max_length=20)),
            ],
        ),
    ]
