# Generated by Django 2.2.15 on 2020-08-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0008_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='name',
            field=models.CharField(default='Academic', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='name',
            field=models.CharField(default='Freelancer', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
